config/routes.rb
Rails.application.routes.draw do
  resources :products
  # devise_for :admins
  # devise_for :users
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end
  root 'top#index'

  get '/users', to: 'users/top#index'

  get '/cart' => 'carts#cart'
  post '/add_item' => 'carts#add_item'
  post '/update_item' => 'carts#update_item'
  post '/delete_item' => 'carts#delete_item'

  get '/order' => 'orders#order'
  post '/order_confirm' => 'orders#confirm'
  post '/order_complete' => 'orders#complete'

  get '/order_history_list' => 'orders#list'
  get 'order_history/:id', to: 'orders#history', as: :order_history

  get '/address_list' => 'addresses#list'
  get '/add_address' => 'addresses#form'
  post '/add_address' => 'addresses#add_address'
  post '/delete_address' => 'addresses#delete_address'

  get '/card_list' => 'cards#list'
  get '/add_card' => 'cards#form'
  post '/add_card' => 'cards#add_card'
  post '/delete_card' => 'cards#delete_card'

  resources :products do
    resource :favorites, only: [:create, :destroy]
  end

  get '/favorite_list' => 'favorites#list'

  # 管理画面
  get '/admins', to: 'admins/top#index'

  namespace :admins do
    resources :products do
      collection do
        get 'search'
      end
    end
    resources :users do
      collection do
        get 'search'
        get 'index'
        get 'show'
      end
    end
    resources :orders do
      collection do
        get 'search'
        get 'index'
        get 'show'
      end
    end
  end

  # 開発環境の場合メール確認ページ
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # :recoverable, :rememberable # deviseのバリデーションは使わない

  attr_accessor :current_password

  # dependent: :destroy は、親のレコードを削除した際に関連する子のレコードも全て削除するための記述
  has_many :favorites, dependent: :destroy
  has_many :cart_items, dependent: :destroy


  # 編集時のみの項目
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :phone_number, presence: true, numericality: { only_integer: true}, format: { with: /\A\d{10,11}\z/ }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :address1, presence: true
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin! # 管理者ログイン必須
  before_action :set_q, only: [:index, :search]

  def index
    @users = @q.result.page(params[:page]).per(10)
  end

  def search
    @results = @q.result.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def set_q
    @q = User.ransack(params[:q])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  before_action :configure_permitted_parameters
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :phone_number, :postal_code, :prefecture, :city, :address1, :address2])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :phone_number, :postal_code, :prefecture, :city, :address1, :address2])
  end

  # ユーザー情報を編集する際にパスワード無しで編集可能に
  # protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/top_controller.rb
class Users::TopController < ApplicationController
  def index
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admins/users/index.html.erb
<h1>会員一覧</h1>

<%= search_form_for @q, url: search_admins_users_path do |f| %>
  <%= f.label :last_name_cont, '名前（姓）' %>
  <%= f.search_field :last_name_cont %>
  <%= f.label :first_name_cont, '名前（名）' %>
  <%= f.search_field :first_name_cont %>
  <br>
  <%= f.submit '検索' %>
<% end %>
<br>
<table>
  <thead>
    <th><%= sort_link(@q, :id, "会員ID") %></th>
    <th><%= sort_link(@q, :last_name, "名前") %></th>
    <th><%= sort_link(@q, :prefecture, "都道府県") %></th>
    <th>アクション</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.last_name %> <%= user.first_name %></td>
      <td><%= user.prefecture %></td>
      <td>
        <%= link_to "詳細", admins_user_path(user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>
<hr>

<br>

<%= link_to "TOPに戻る", admins_path %>

app/views/admins/users/search.html.erb
<h1>会員一覧</h1>

<%= search_form_for @q, url: search_admins_users_path do |f| %>
  <%= f.label :last_name_cont, '名前（姓）' %>
  <%= f.search_field :last_name_cont %>
  <%= f.label :first_name_cont, '名前（名）' %>
  <%= f.search_field :first_name_cont %>
  <br>
  <%= f.submit '検索' %>
<% end %>
<br>
<table>
  <thead>
    <th><%= sort_link(@q, :id, "会員ID") %></th>
    <th><%= sort_link(@q, :last_name, "名前") %></th>
    <th><%= sort_link(@q, :prefecture, "都道府県") %></th>
    <th>アクション</th>
  </thead>
  <tbody>
    <% @results.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.last_name %> <%= user.first_name %></td>
      <td><%= user.prefecture %></td>
      <td>
        <%= link_to "詳細", admins_user_path(user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @results %>
<hr>

<br>

<%= link_to "TOPに戻る", admins_path %>

app/views/admins/users/show.html.erb
<h1>会員詳細</h1>

<table>
  <tr>
    <th>会員ID</th>
    <td><%= @user.id %></td>
  </tr>
  <tr>
    <th>名前</th>
    <td><%= @user.last_name %> <%= @user.first_name %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td><%= @user.phone_number %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td>
      〒<%= @user.postal_code %><br>
      <%= @user.prefecture %><%= @user.city %><%= @user.address1 %><%= @user.address2 %>
    </td>
  </tr>
</table>

<div>
  <br>
  <%= link_to "会員一覧に戻る", admins_users_path %>
</div>