config/routes.rb
Rails.application.routes.draw do
  resources :products
  # devise_for :admins
  # devise_for :users
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end
  root 'top#index'

  get '/users', to: 'users/top#index'

  get '/cart' => 'carts#cart'
  post '/add_item' => 'carts#add_item'
  post '/update_item' => 'carts#update_item'
  post '/delete_item' => 'carts#delete_item'

  get '/order' => 'orders#order'
  post '/order_confirm' => 'orders#confirm'
  post '/order_complete' => 'orders#complete'

  get '/order_history_list' => 'orders#list'
  get 'order_history/:id', to: 'orders#history', as: :order_history

  get '/address_list' => 'addresses#list'
  get '/add_address' => 'addresses#form'
  post '/add_address' => 'addresses#add_address'
  post '/delete_address' => 'addresses#delete_address'

  get '/card_list' => 'cards#list'
  get '/add_card' => 'cards#form'
  post '/add_card' => 'cards#add_card'
  post '/delete_card' => 'cards#delete_card'

  resources :products do
    resource :favorites, only: [:create, :destroy]
  end

  get '/favorite_list' => 'favorites#list'

  # 管理画面
  get '/admins', to: 'admins/top#index'

  namespace :admins do
    resources :products do
      collection do
        get 'search'
      end
    end
    resources :users do
      collection do
        get 'search'
        get 'index'
        get 'show'
      end
    end
    resources :orders do
      collection do
        get 'search'
        get 'index'
        get 'show'
      end
    end
  end

  # 開発環境の場合メール確認ページ
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def cart
    @cart_items = CartItem.where(user_id: current_user.id)
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
  end

  def add_item
    if user_signed_in?
      @cart_item = CartItem.new(user_id: current_user.id, product_id: params[:product_id], quantity: params[:quantity])
      @cart_item.save
    else
      # 未ログイン時はセッションに
    end
    redirect_to product_path(params[:product_id])
  end

  def update_item
    @cart_item = CartItem.find_by(user_id: current_user.id, product_id: params[:product_id])
    @cart_item.update(quantity: params[:quantity])
    redirect_to cart_path
  end

  def delete_item
    @cart_item = CartItem.find_by(user_id: current_user.id, product_id: params[:product_id])
    @cart_item.destroy
    # 遷移元取得
    @path = Rails.application.routes.recognize_path(request.referer)
    # 注文画面から来ていた場合は注文画面へリダイレクト
    if @path[:controller] == 'carts'
      redirect_to cart_path()
    else
      redirect_to product_path(params[:product_id])
    end
  end
end

app/views/carts/cart.html.erb
<h1>カート</h1>

<p style="color: red"><%= flash[:out_of_stock] %></p>

<h2>商品一覧</h2>

<% if @cart_items.blank? %>
  <p>カートに入っている商品はありません。</p>
<% else %>
  <% @cart_items.each do |cart_item| %>

  <li class="list-none">
      <%= cart_item.product.name %>
      <%= "#{cart_item.product.price}円" %>
      <%= form_with(url: update_item_url, method: :post,local: true) do |f| %>
      <%= f.hidden_field :product_id, value: cart_item.product.id %>
      <select name="quantity">
        <% (1..cart_item.product.stock).each do |i| %>
        <option value="<%= i %>" <% if i == cart_item.quantity %>selected<% end %>><%= i %></option>
        <% end %>
      </select>
      <%= f.submit "更新", class: "" %>
      <% end %>
      <%= button_to "削除", delete_item_path(product_id: cart_item.product.id), method: :post, data: { confirm: "商品を削除しますか？" } %>
  </li>

  <% end %>

  <h2><%= "合計：#{@total}円" %></h2>

  <%= link_to "注文画面へ進む", order_path %>

<% end %>
<br>
<br>
<%= link_to "TOPに戻る", root_path %>