config/routes.rb
Rails.application.routes.draw do
  resources :products
  # devise_for :admins
  # devise_for :users
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/users/sign_out' => 'users/sessions#destroy'
  end
  root 'top#index'

  get '/users', to: 'users/top#index'

  get '/cart' => 'carts#cart'
  post '/add_item' => 'carts#add_item'
  post '/update_item' => 'carts#update_item'
  post '/delete_item' => 'carts#delete_item'

  get '/order' => 'orders#order'
  post '/order_confirm' => 'orders#confirm'
  post '/order_complete' => 'orders#complete'

  get '/order_history_list' => 'orders#list'
  get 'order_history/:id', to: 'orders#history', as: :order_history

  get '/address_list' => 'addresses#list'
  get '/add_address' => 'addresses#form'
  post '/add_address' => 'addresses#add_address'
  post '/delete_address' => 'addresses#delete_address'

  get '/card_list' => 'cards#list'
  get '/add_card' => 'cards#form'
  post '/add_card' => 'cards#add_card'
  post '/delete_card' => 'cards#delete_card'

  resources :products do
    resource :favorites, only: [:create, :destroy]
  end

  get '/favorite_list' => 'favorites#list'

  # 管理画面
  get '/admins', to: 'admins/top#index'

  namespace :admins do
    resources :products do
      collection do
        get 'search'
      end
    end
    resources :users do
      collection do
        get 'search'
        get 'index'
        get 'show'
      end
    end
    resources :orders do
      collection do
        get 'search'
        get 'index'
        get 'show'
      end
    end
  end

  # 開発環境の場合メール確認ページ
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def list
    # @cards = Card.where(user_id: current_user.id)
    card = Card.find_by(user_id: current_user.id)
    if card.nil?
      @cards = nil
    else
      Payjp.api_key = ENV['PAYJP_SECRET_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @cards = customer.cards.all()
    end
  end

  def form
    # 遷移元取得
    @path = Rails.application.routes.recognize_path(request.referer)
    # 遷移元コントローラー名をセッションに入れる
    session[:previous_controller] = @path[:controller]
    logger.error(session[:previous_controller])
  end

  def add_card
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    card = Card.find_by(user_id: current_user.id)
    if card.nil?
      # 顧客未登録
      customer = Payjp::Customer.create(
        description: 'test',
        card: params[:token_id]
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
    else
      # 顧客登録済み
      customer = Payjp::Customer.retrieve(card.customer_id)
      new_card = customer.cards.create(
        card: params[:token_id]
      )
      @card = Card.new(user_id: current_user.id, customer_id: card.customer_id, card_id: new_card.id)
    end

    # respond_to do |format|
      if @card.save
        if session[:previous_controller] == 'orders'
          path = '/order'
        else
          path = '/card_list'
        end
        render json: {
          :path => path
        }
      else
        format.html
        format.json
      end
    # end
  end

  def delete_card
    card = Card.find_by(user_id: current_user.id)
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.retrieve(card.customer_id)
    card = customer.cards.retrieve(params[:card_id])
    card.delete
    @card = Card.find_by(card_id: params[:card_id])
    @card.destroy
    redirect_to card_list_path()
  end

end

app/views/cards/form.html.erb
<h1>クレジットカードの新規登録</h1>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://js.pay.jp/v2/pay.js"></script>
<style>
/* 必要に応じてフォームの外側のデザインを用意します */
div.payjs-outer {
  border: thin solid #198fcc;
  width: 360px;
}
</style>

<%= csrf_meta_tags %>

<div id="v2-demo" class="payjs-outer"><!-- ここにフォームが生成されます --></div>
<br>
<button onclick="onSubmit(event)">カードを登録する</button>

<script>
// 公開鍵を登録し、起点となるオブジェクトを取得します
var payjp = Payjp('pk_test_9174f41f1eef7934c556e3f4')

// elementsを取得します。ページ内に複数フォーム用意する場合は複数取得ください
var elements = payjp.elements()

// element(入力フォームの単位)を生成します
var cardElement = elements.create('card')

// elementをDOM上に配置します
cardElement.mount('#v2-demo')

// ボタンが押されたらtokenを生成する関数を用意します
function onSubmit(event) {
  $('this').prop('disabled', true);
  payjp.createToken(cardElement).then(function(r) {
    // document.querySelector('#token').innerText = r.error ? r.error.message : r.id
    if (r.error) {
      alert(r.error.message);
      return
    }
    $.ajax({
      type: "POST",
      url: "/add_card",
      data: { "token_id" : r.id },
      dataType : "json",
      headers: {
        'X-CSRF-Token' : $('meta[name="csrf-token"]').attr('content')
      },
    }).done(function(data){
      console.log(data.path);
      window.location.href = data.path;
    }).fail(function(XMLHttpRequest, status, e){
      alert(e);
    });
  })
}
</script>

<br>
<br>
<br>
<% if session[:previous_controller] == 'orders' %>
  <%= link_to "注文画面に戻る", order_path %>
<% else %>
  <%= link_to "クレジットカード一覧に戻る", card_list_path %>
<% end %>

app/views/cards/list.html.erb
<h1>クレジットカード一覧</h1>



<% if @cards.nil? %>
  <p>登録済みのクレジットカードはありません。</p>
  <%= link_to '新規登録', add_card_path %>
<% else %>
  <% @cards.each do |card| %>

  <hr>

  <li class="list-none">
      <%= card.brand %><br>
      **** **** **** <%= card.last4 %><br>
      <%= card.exp_month %>月/<%= card.exp_year %>年<br>
      <%= button_to "削除", delete_card_path(card_id: card.id), method: :post, data: { confirm: "商品を削除しますか？" } %>
  </li>

  <% end %>
  <hr>
  <%= link_to '追加登録', add_card_path %>
<% end %>
<br>
<br>
<%= link_to "TOPに戻る", root_path %>